services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    networks:
      - app-network

  # app:
  #   build: .
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=yourpassword
  #   networks:
  #     - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
