services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-tdk
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: tdk-db
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - redis
      - mongo
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs

volumes:
  redis-data:
  mongo-data:

networks:
  app-network:
    driver: bridge
