services:
  redis:
    image: redis
    container_name: redis-tdk
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo-tdk
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  redis-data:
  mongo-data:

networks:
  app-network:
    driver: bridge
